### ISSUE TITLE
Create a component for profile picture

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/solstice-assets#150]
![Screen Shot 2020-06-22 at 3 54 18 PM](https://user-images.githubusercontent.com/893942/85329462-93766b80-b4a0-11ea-8a66-090490693f08.png)

Let's create a component for these profiles pictures! This is something that we should be able to use outside of the owl.carousel.

Can this be something as simple as a class on the img tag such as .profile-img-circle ?

**Comment by flora8984461** [comment]
Does not this style already exists? https://events.eclipse.org/2020/open-source-ai-workshop/  🤔

![image](https://user-images.githubusercontent.com/39588094/96275652-fb951400-0f9f-11eb-9e9a-30eb6719df79.png)

**Comment by chrisguindon** [comment]
@flora8984461 +1
