### ISSUE TITLE
Asynchronous calls crash javascript in IE

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/solstice-assets#174]
Currently, none of the sites that make use of this script have working Javascript on IE. This is due to the fact that the `async` keyword\functionality is not supported in internet explorer (at all). https://caniuse.com/async-functions

**Comment by chrisguindon** [comment]
I created https://github.com/EclipseFdn/solstice-assets/pull/175 to limit the impact of this bug.

**Comment by autumnfound** [comment]
This was closed same day
