### ISSUE TITLE
Eclipse.org home page - background image update

### ISSUE THREAD

**Issue by meKokabi** [EclipseFdn/solstice-assets#217]
Please Update the Homepage bkg image. We are hoping to have the update by tomorrow, and sorry for short notice.

![homepage](https://user-images.githubusercontent.com/75500459/104516133-db3a1d00-55c1-11eb-9093-eab93fa8d635.jpg)

page link: https://www.eclipse.org/

**Comment by chrisguindon** [comment]
The text on subpages, where the text is not bolded is not  readable:

For example: https://staging.eclipse.org/org/workinggroups/

@meKokabi Would you recommend that we bold the text on all pages?

**Comment by flora8984461** [comment]
Hi @meKokabi 
Can you please also advise on improvements for the preview: https://staging.eclipse.org/projects/  Thanks!

The "list of all projects" seems less accessible. 

![image](https://user-images.githubusercontent.com/39588094/104763390-ca111d80-5733-11eb-9f6d-3d430375798f.png)

**Comment by meKokabi** [comment]
@chrisguindon @flora8984461 Thanks for being so detail oriented, and offering useful feedback. I believe we can make it bold. As it has accessibility issue with the current one as well.
<img width="1564" alt="Screen Shot 2021-01-15 at 1 20 14 PM" src="https://user-images.githubusercontent.com/75500459/104763960-b1553780-5734-11eb-85de-cd284b60c780.png">

**Comment by chrisguindon** [comment]
@meKokabi Correct! We did notice after that this is currently an issue. We decided to move forward with this since it's not a new problem. 

We plan on collaborating with you on this problem via issue #221
