### ISSUE TITLE
[Accessibility] On project page, the "project list" link is less accessible

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/solstice-assets#221]
This issue is inpired by https://github.com/EclipseFdn/solstice-assets/issues/217

![image](https://user-images.githubusercontent.com/39588094/104766801-27f43400-5739-11eb-93bc-b1ceaa78b987.png)

**Comment by meKokabi** [comment]
@chrisguindon I understand you assigned this issue to me, please guide me on how would you like me to take action. Shall I make adjustment here or you like me to. increase the image contrast.
Thanks,

**Comment by chrisguindon** [comment]
You and Yi are assigned to this.

This simply means that expect you both to collaborate on this problem togheter!

**Comment by meKokabi** [comment]
Absolutely!

**Comment by meKokabi** [comment]
@flora8984461 Hi Yi, I made some additional changes to make the centre more darker and accessible. Please check  and let me know if this can resolve the issue. Thanks for your help!
![homepageFinal](https://user-images.githubusercontent.com/75500459/104775758-e79bb280-5746-11eb-9f87-33d21ef3c8fc.jpg)

**Comment by flora8984461** [comment]
Hi @meKokabi  Thanks for your help on the image. But since the image position/size changes according to the screen size, we actually think to change the link color. 

I made an example here, I used the new image you attached, and added other 2 example links, one is a white link, one is a button, I'm not sure if it's better, or do you have any other suggestions?

https://deploy-preview-222--eclipsefdn-solstice-assets.netlify.app/

Thank you!

screenshot attached:

![image](https://user-images.githubusercontent.com/39588094/104783764-bcb85b00-5754-11eb-941e-4652e474943f.png)

**Comment by meKokabi** [comment]
Hello, I believe the white links/ fonts work very well.

**Comment by chrisguindon** [comment]
@flora8984461 @meKokabi,

I created a mock up to illustrate what I had in mind. I find it's easier to describe design ideas with an image:

![Screenshot from 2021-01-18 09-10-54](https://user-images.githubusercontent.com/893942/104925749-39258680-596d-11eb-8b7a-bb253ce9db64.png)

Key takeaway:

- Make the search box visible since it's not clear to all users that this is an input field for the search.
- Improve contrast on View All Projects link

**Comment by meKokabi** [comment]
Looks good to me! Appreciated!

**Comment by flora8984461** [comment]
Thanks for all your feedback!
I have updated my branch and the preview: https://deploy-preview-222--eclipsefdn-solstice-assets.netlify.app/?utm_source=github&utm_campaign=bot_dp

I don't think we need to update the header image again to use this? https://github.com/EclipseFdn/solstice-assets/issues/221#issuecomment-761183342

Please let me know if you still want to use this new image. @meKokabi  Thanks!

**Comment by meKokabi** [comment]
Thanks! Looks good to me!
