### ISSUE TITLE
Remove usage of Babel in the solstice assets webpack config

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/solstice-assets#227]
As part of making our codebase more robust and straightforward, we are removing Babel. This is due to `min.babel` not polyfilling, and `mix.js` creating issues with modularity and breaking some of our code which expects variables to be available. In doing this, we should remove any es6 features we've added in the meantime unless strictly necessary.

**Comment by ericpoirier** [comment]
Hi @autumnfound, is this still an issue?

**Comment by autumnfound** [comment]
Nope! This was a suggestion in the past as the babel implementation had some holes in it and was causing more issues than it was solving. Chris has fully implemented babel into our stack, so we should be able to close this
