### ISSUE TITLE
Improve typography

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/solstice-assets#67]
We would like to improve the spacing for headings in solstice-assets to make the text easier to read.

Here's an example of a text heavy page:
https://www.eclipse.org/eclipse.org-common/themes/solstice/docs/typo.php

This page is missing a bit of separation between each section. We also think that updating the font-weight from 200 to 400 for headings will help us improve readability.

This task will requires us to consider the context of each heading since I think we might want a different margin/padding value based off the previous/next element. 

For example, we might want a different margin/padding value for an h2 if the next element is a h3 instead of a p.

**Comment by ChristieWittEclipse** [comment]
+1 I will add this to my backlog.

**Comment by ChristieWittEclipse** [comment]
@chrisguindon I've reviewed the typography now that we've deployed the Roboto font family and I'm happy with it. We can close this issue.

**Comment by chrisguindon** [comment]
Thank you very much @ChristieWittEclipse
