### ISSUE TITLE
Featured story block shows background image on ultrawide displays

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/solstice-assets#79]
Fix would be something like adding 50vw to the ad content background instead of 1000px, and adding overflow-x: hidden to mask any potential overflow.
![image](https://user-images.githubusercontent.com/23018241/59932364-fc9e4b80-9414-11e9-8688-6943c5d8ce73.png)

**Comment by chrisguindon** [comment]
Thanks @autumnfound
